name: CI Develop

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build and test Docker containers
      run: |
        docker-compose -f docker-compose.yml -f docker-compose.override.yml --env-file .env.develop up --build -d
        docker-compose ps
        docker-compose logs -f

    - name: Run tests
      run: |
        docker-compose exec ai-service pytest ./ai-service/tests/
        docker-compose exec log-watcher pytest ./log-watcher/tests/
        docker-compose exec ci-cd-automation pytest ./ci-cd-automation/tests/
