name: CI Test and Build

on:
  push:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build Docker containers
      run: |
        docker-compose -f docker-compose.yml --env-file .env.develop up --build
        docker-compose down

    - name: Run tests
      run: |
        docker-compose -f docker-compose.yml exec ai-service pytest ./ai-service/tests/
